# Generated by Django 4.2 on 2023-04-11 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userReg', '0002_alter_characters_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buddies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('whale', 'Whale'), ('turtle', 'Turtle'), ('dolphin', 'Dolphin'), ('seal', 'Seal'), ('seagull', 'Seagull')], max_length=50)),
                ('picture', models.ImageField(upload_to='buddies/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
