# Generated by Django 4.2 on 2023-04-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userReg', '0003_buddies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddies',
            name='picture',
            field=models.ImageField(upload_to='static/images/profilePictures'),
        ),
    ]
