# Generated by Django 4.1.7 on 2023-03-15 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_posts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='postComment',
        ),
    ]
